spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 之后的填写mybatis的mapper书写路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
